---
baseURL: "https://kevinkwl.github.io/"
disablePathToLower: true
languageCode: en-us
title: "Kangwei Ling"
pluralizelisttitles: "false"
footnoteReturnLinkContents: "^"

params:
  description: "Coder Reader Runner"
  author:
    name: Kevin Ling
    email: lingkangwei.kevin@gmail.com
  imgurl: "/assets/img/"
  disqus: "winds-howling"
  copyright: "Kevin Ling, kevinkwl"
  github: "kevinkwl"
  homebg: "home-bg.jpg"

social:
  github: "kevinkwl"
  linkedin: "kangwei-ling-520aab131"


googleAnalytics: "UA-98612858-1"

# include this sections in writing index.
indexInclude:
  - essays
  - misc
  - notes

taxonomies:
  tag: "tags"
  category: "category"

ignoreFiles:
  - /_output
  - /_public
  - /_img
  - /_less
  - /.git
  - /_styl
  - README.org

MetaDataFormat: "yaml"

blackfriday:
  plainIDAnchors: true
  extensions:
  - hardLineBreak
