#+TITLE: Keep process running via Screen
#+Author: Kangwei Ling
#+DATE: 2016-11-19
#+Description: screen
#+TAGS: Linux
#+category: Notes
#+OPTIONS: num:nil ^:nil toc:nil
Recently I've been trying to train a neural network for machine translation
([[https:github.com/rsennrich/nematus][nematus]]) using the linux machine of the laboratory via ssh shell. But it keeps
annoying me that each time I close the ssh connection, the training process
terminates. As the training process is initiated from ssh shell, it is a child
process that will be terminates when the parent process terminates (I exit the
ssh shell).

The recommended way is to use =screen=, which it can create processes in
different process groups, thereby keep the processes running even if you
disconnect from ssh session.

* Installation
On Ubuntu:
#+BEGIN_SRC bash
sudo apt-get install screen
#+END_SRC
will install =screen=. Other Linux distributions can use their package managers
instead.

* Simple usage
On normal shell session, =~$screen= will open up the Screen Manager, then press
the key =SPACE= or =RETURN= will start a screen window. A screen window is just
like a shell, however, you can attach or detach to it without killing the
session.

In a screen window, type the usual command to start the process, then =C-a d=
(=C= stands for Control Key) will detach you from the current screen window session (send you back to the
original shell).

The command =$screen -ls= can list all screen windows, and use =$screen -r
name-of-window= to reattach to that window, e.g.:
#+BEGIN_SRC bash
$ screen -ls
There are screens on:
	835.pts-22.mercury	(11/19/16 19:15:27)	(Detached)
	11375.pts-22.mercury	(11/19/16 16:32:05)	(Detached)
2 Sockets in /var/run/screen/S-linkw.

$ screen -r 835.pts-22.mercury
#+END_SRC
To kill a screen session, just hit =C-a k=, or =C-a= then enter =:quit= if you
are in an attached window. Also,
#+BEGIN_SRC bash
$ screen -X -S [session # you want to kill] quit
#+END_SRC
works.

For more usages, use =$man screen= to see man page. A full manual can be found
at [[https://www.gnu.org/software/screen/manual/][GNU Screen]].
